name: Publish from Branch
on:
  workflow_call:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      # We need to explicitly checkout the publish branch
      - uses: actions/checkout@v2
        branch: adf_publish

      - name: Publish to Dev
        run: |
          ls
