name: Publish from Branch
on:
  workflow_call:

jobs:
  publish-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # This step is the key.  Even though we are running from a workflow file that exists in main,
      # we need to do the processing (deployments) based on the files in the branch.
      # You'll need this checkout statement in each job that will deploy from the branch.
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: adf_publish

      # This is just a place holder for the real work tha that you need to do...
      - name: Publish to Dev
        run: |
          ls

  publish-to-preprod:
    runs-on: ubuntu-latest
    needs: [ publish-to-dev ]
    environment: preprod
    steps:
      # (Repeated here, as mentioned above)
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: adf_publish

      # This is just a place holder for the real work tha that you need to do...
      - name: Publish to Pre-prod
        run: |
          ls

