name: Publish from Branch
on:
  workflow_call:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      # We need to explicitly checkout the publish branch
      
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: adf_publish
      #     path: # optional

      - name: Publish to Dev
        run: |
          ls
