on:
  workflow_dispatch:
  push:
    branches: [ adf_publish ]

jobs:
  promote:
    name: Promote branch changes to environments
    uses: dmckinstry/SeparateBranchBuild/.github/workflows/deploy-from-main.yml@main
